name: backend-ci

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4
      
      # 2. Java 세팅
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          
      # 3. gradlew 권한
      - name: Grant Permission
        run: chmod +x gradlew
        
      # 4. 빌드
      - name: Build
        run: ./gradlew build

      # 5. 테스트
      - name: Run tests
        run: ./gradlew test
