name: frontend-ci

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: #CI-CDpart/frontend

    steps:
      # 1. 코드 가져오기
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # 2. Node 세팅
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      # 3. 의존성 설치 (로그 보기 좋게)
      - name: Install dependencies
        run: npm ci --verbose

      # 4. 빌드 (로그 강화)
      - name: Build project
        run: npm run build --loglevel verbose
