spring:
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

jwt:
  secret: this_is_a_very_long_secret_key_for_jwt_signing_123456
  expiration: 3600000

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

  endpoint:
    health:
      slow-details: always

